language: rust
os: windows

env:
  - MIX=C:\\ProgramData\\chocolatey\\lib\\Elixir\\bin\\mix.bat

install:
  - choco install elixir
  - $MIX local.hex --force

jobs:
  include:
    - stage: test
      script:
        - $MIX deps.get
        - $MIX compile --force --warnings-as-errors
        - $MIX credo --strict --ignore TrailingWhiteSpace --ignore LineEndings
        - $MIX test
    - stage: deploy
      if: branch = master AND type = push AND fork = false
      script:
        - $MIX deps.get
        - $MIX hex.publish --yes
