language: rust
os: windows

env:
  - MIX=C:\\ProgramData\\chocolatey\\lib\\Elixir\\bin\\mix.bat

install:
  - choco install elixir

script:
  - $MIX local.hex --force
  - $MIX deps.get
  - $MIX hex.publish --yes
